name: IAC Pipeline

on:
  push:
    branches: 
      - main

jobs:
  terraform-exec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@4.2.2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"
      - name: Execução do terraform init
        run: terraform init
        working-directory: ./src
      - name: Execução do terraform validate
        run: terraform validate
        working-directory: ./src
      - name: Execução do terraform apply
        run: terraform apply --auto-approve
        working-directory: ./src
